//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address cannot be null  for ProfileAddress.
        /// </summary>
        internal static string exception_ProfileAddressCannotAssociateNullAddress {
            get {
                return ResourceManager.GetString("exception_ProfileAddressCannotAssociateNullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AddressType cannot be null  for ProfileAddress.
        /// </summary>
        internal static string exception_ProfileAddressCannotAssociateNullAddressType {
            get {
                return ResourceManager.GetString("exception_ProfileAddressCannotAssociateNullAddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Profile cannot be null  for ProfileAddress.
        /// </summary>
        internal static string exception_ProfileAddressCannotAssociateNullProfile {
            get {
                return ResourceManager.GetString("exception_ProfileAddressCannotAssociateNullProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City cannot be null  for Address.
        /// </summary>
        internal static string exception_ProfileCannotAssociateNullCity {
            get {
                return ResourceManager.GetString("exception_ProfileCannotAssociateNullCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone cannot be null  for ProfilePhone.
        /// </summary>
        internal static string exception_ProfilePhoneCannotAssociateNullPhone {
            get {
                return ResourceManager.GetString("exception_ProfilePhoneCannotAssociateNullPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PhoneType cannot be null  for ProfilePhone.
        /// </summary>
        internal static string exception_ProfilePhoneCannotAssociateNullPhoneType {
            get {
                return ResourceManager.GetString("exception_ProfilePhoneCannotAssociateNullPhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Profile cannot be null  for ProfilePhone.
        /// </summary>
        internal static string exception_ProfilePhoneCannotAssociateNullProfile {
            get {
                return ResourceManager.GetString("exception_ProfilePhoneCannotAssociateNullProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address Line 1 cannot be null or empty string for Address.
        /// </summary>
        internal static string validation_AddressAddressLine1CannotBeNull {
            get {
                return ResourceManager.GetString("validation_AddressAddressLine1CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address Line 2 cannot be null or empty string for Address.
        /// </summary>
        internal static string validation_AddressAddressLine2CannotBeBull {
            get {
                return ResourceManager.GetString("validation_AddressAddressLine2CannotBeBull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City  in Address cannot be empty for Address.
        /// </summary>
        internal static string validation_AddresscityCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_AddresscityCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Country in Address cannot be empty for Address.
        /// </summary>
        internal static string validation_AddressCountryCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_AddressCountryCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The State in Address cannot be empty for Address.
        /// </summary>
        internal static string validation_AddressStateCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_AddressStateCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number cannot be null  for Phone.
        /// </summary>
        internal static string validation_PhoneNumberCannotBeNull {
            get {
                return ResourceManager.GetString("validation_PhoneNumberCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address ID  in ProfileAddress cannot be empty.
        /// </summary>
        internal static string validation_ProfileAddressAddressIDCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_ProfileAddressAddressIDCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address Type ID  in ProfileAddress cannot be empty.
        /// </summary>
        internal static string validation_ProfileAddressAddressTypeIDCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_ProfileAddressAddressTypeIDCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Profile  ID  in ProfileAddress cannot be empty.
        /// </summary>
        internal static string validation_ProfileAddressProfileIDCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_ProfileAddressProfileIDCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email cannot be null or empty string for Profile.
        /// </summary>
        internal static string validation_ProfileEmailCannotBeBull {
            get {
                return ResourceManager.GetString("validation_ProfileEmailCannotBeBull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Name cannot be null or empty string for Profile.
        /// </summary>
        internal static string validation_ProfileFirstNameCannotBeNull {
            get {
                return ResourceManager.GetString("validation_ProfileFirstNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Name cannot be null or empty string for Profile.
        /// </summary>
        internal static string validation_ProfileLastNameCannotBeBull {
            get {
                return ResourceManager.GetString("validation_ProfileLastNameCannotBeBull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone  ID  in ProfileAddress cannot be empty.
        /// </summary>
        internal static string validation_ProfilePhonePhoneIDCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_ProfilePhonePhoneIDCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PhoneType  ID  in ProfileAddress cannot be empty.
        /// </summary>
        internal static string validation_ProfilePhonePhoneTypeIDCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_ProfilePhonePhoneTypeIDCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Profile  ID  in ProfileAddress cannot be empty.
        /// </summary>
        internal static string validation_ProfilePhoneProfileIDCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_ProfilePhoneProfileIDCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Zip Code cannot be null or empty string for Address.
        /// </summary>
        internal static string validation_ZipCodeCannotBeBull {
            get {
                return ResourceManager.GetString("validation_ZipCodeCannotBeBull", resourceCulture);
            }
        }
    }
}
